### PR TITLE
Update Travis

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/30)

### CODE REVIEW

**Comment by ldorau** [comment]
@lukaszstolarczuk @igchor please review

**Review by lukaszstolarczuk — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/30#-:-LqeTC3y-Yd6yQLnpiqV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by igchor — COMMENTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/30)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[utils/docker/images/Dockerfile.ubuntu-19.04, line 76 at r2](https://reviewable.io/reviews/pmem/pmemkv-jni/30#-Lr7vH7kErZUL-U53Rx7:-Lr7vH7l9WF7ThBUlmaX:b-epwcal) ([raw file](https://github.com/pmem/pmemkv-jni/blob/8a571acfb1a4dbe1fd0d2d86d3e3a6abeca9ae44/utils/docker/images/Dockerfile.ubuntu-19.04#L76)):*
> ```
> 
> # Install Googletest
> COPY install-googletest.sh install-googletest.sh
> ```

Maybe instead of copying install-googletest.sh we could just copy the cmake logic for finding gtest package (just to use on system-installed package)?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/30)* status: 3 of 8 files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[utils/docker/images/Dockerfile.ubuntu-19.04, line 76 at r2](https://reviewable.io/reviews/pmem/pmemkv-jni/30#-Lr7vH7kErZUL-U53Rx7:-Lr9NyTk2bFO9fckhoRv:b-896fix) ([raw file](https://github.com/pmem/pmemkv-jni/blob/8a571acfb1a4dbe1fd0d2d86d3e3a6abeca9ae44/utils/docker/images/Dockerfile.ubuntu-19.04#L76)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Maybe instead of copying install-googletest.sh we could just copy the cmake logic for finding gtest package (just to use on system-installed package)?
</blockquote></details>

Done.

**Review by lukaszstolarczuk — APPROVED** [review]
:lgtm:

> Reviewed 5 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/30#-:-LrNPCuY5VfdP-MndSiP:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/30)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor and @ldorau)

___
*[CMakeLists.txt, line 53 at r3](https://reviewable.io/reviews/pmem/pmemkv-jni/30#-LrhIZJ-A6T0BBLox5Y6:-LrhIZJ-A6T0BBLox5Y7:bdmczyo) ([raw file](https://github.com/pmem/pmemkv-jni/blob/7536b4f1b8f5c53573058d13499e0a4dbf973e55/CMakeLists.txt#L53)):*
> ```CMake
> 
> add_executable(pmemkv-jni_test src/pmemkv-jni_test.cc)
> target_link_libraries(pmemkv-jni_test pmemkv gtest pthread)
> ```

as for gtest you can apply a similar patch to one we've introduced in pmemkv:
https://github.com/pmem/pmemkv/commit/074b27ace6d2c4d2e79af9003fa6728c20c1d7bd

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/30)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[CMakeLists.txt, line 53 at r3](https://reviewable.io/reviews/pmem/pmemkv-jni/30#-LrhIZJ-A6T0BBLox5Y6:-LrhdiQn5LO9P-ye5_B4:b-896fix) ([raw file](https://github.com/pmem/pmemkv-jni/blob/7536b4f1b8f5c53573058d13499e0a4dbf973e55/CMakeLists.txt#L53)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

as for gtest you can apply a similar patch to one we've introduced in pmemkv:
https://github.com/pmem/pmemkv/commit/074b27ace6d2c4d2e79af9003fa6728c20c1d7bd
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/30)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor and @ldorau)

___
*[CMakeLists.txt, line 69 at r4](https://reviewable.io/reviews/pmem/pmemkv-jni/30#-Lrhy7it31SM18Woz5Hu:-Lrhy7it31SM18Woz5Hv:b-ht7py2) ([raw file](https://github.com/pmem/pmemkv-jni/blob/9f38277f29b347c392719209852900d66d5e2c82/CMakeLists.txt#L69)):*
> ```CMake
> 	set_target_properties(libgtest PROPERTIES "IMPORTED_LOCATION" "${GTEST}"
> 		"IMPORTED_LINK_INTERFACE_LIBRARIES" "${CMAKE_THREAD_LIBS_INIT}")
> 	target_link_libraries(pmemkv-jni_test pmemkv libgtest pthread)
> ```

pmemkv and pthread are only needed if gtest is found?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/30)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[CMakeLists.txt, line 69 at r4](https://reviewable.io/reviews/pmem/pmemkv-jni/30#-Lrhy7it31SM18Woz5Hu:-Lri4GmP0URJPYh85kbH:b-75l2x7) ([raw file](https://github.com/pmem/pmemkv-jni/blob/9f38277f29b347c392719209852900d66d5e2c82/CMakeLists.txt#L69)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pmemkv and pthread are only needed if gtest is found?
</blockquote></details>

No. Linking makes sense only if there is gtest installed, otherwise there is a FATAL_ERROR.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/30)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor and @ldorau)

___
*[CMakeLists.txt, line 69 at r4](https://reviewable.io/reviews/pmem/pmemkv-jni/30#-Lrhy7it31SM18Woz5Hu:-LrsxvNx6s2L-58fv1gt:b-8zgflu) ([raw file](https://github.com/pmem/pmemkv-jni/blob/9f38277f29b347c392719209852900d66d5e2c82/CMakeLists.txt#L69)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

No. Linking makes sense only if there is gtest installed, otherwise there is a FATAL_ERROR.
</blockquote></details>

make sense, thanks
___
*[utils/docker/images/prepare-pmemkv.sh, line 55 at r5](https://reviewable.io/reviews/pmem/pmemkv-jni/30#-Lrszf-o0MjWDhOuWREg:-Lrszf-p7Q9QuNBDa0KS:b-3ty5hu) ([raw file](https://github.com/pmem/pmemkv-jni/blob/b9990cecc515b522ba86d11ed2c9a32cbef1a5f7/utils/docker/images/prepare-pmemkv.sh#L55)):*
> ```Shell
> 		-DCMAKE_INSTALL_PREFIX=$PREFIX \
> 		-DCPACK_GENERATOR=$package_type \
> 		-DTESTS_USE_VALGRIND=OFF
> ```

why turning of Valgrind tests? if you don't want to build & run tests then just BUILD_TESTS=OFF

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/30)* status: 7 of 8 files reviewed, 2 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[utils/docker/images/prepare-pmemkv.sh, line 55 at r5](https://reviewable.io/reviews/pmem/pmemkv-jni/30#-Lrszf-o0MjWDhOuWREg:-Lrt0fHjCOMWnAw8yKc2:b-896fix) ([raw file](https://github.com/pmem/pmemkv-jni/blob/b9990cecc515b522ba86d11ed2c9a32cbef1a5f7/utils/docker/images/prepare-pmemkv.sh#L55)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why turning of Valgrind tests? if you don't want to build & run tests then just BUILD_TESTS=OFF
</blockquote></details>

Done.

**Review by lukaszstolarczuk — APPROVED** [review]
Perhaps we can wait and merge after pmemkv tag 1.0.1 is delivered, but it looks good

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/30#-:-Lrt1DwG-MkCPjoC9BOH:bm2kp47)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/30)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[utils/docker/images/Dockerfile.ubuntu-19.04, line 76 at r2](https://reviewable.io/reviews/pmem/pmemkv-jni/30#-Lr7vH7kErZUL-U53Rx7:-Lrt5G4pDHzH8fGT2jxw:buzi8io) ([raw file](https://github.com/pmem/pmemkv-jni/blob/8a571acfb1a4dbe1fd0d2d86d3e3a6abeca9ae44/utils/docker/images/Dockerfile.ubuntu-19.04#L76)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@igchor ?

**Comment by ldorau** [comment]
@igchor please resolve your issue and merge

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, 5 of 6 files at r3, 1 of 4 files at r5, 6 of 6 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/30#-:-LsRJhsP5tKhKYXJuBfH:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by lukaszstolarczuk — APPROVED** [review]
> Reviewed 6 of 6 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/30)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
