### PR TITLE
Update Travis files

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
- add Fedora image (v. 31)
- minor cleanup and pmemkv version update

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/33)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/33)* status: all files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[utils/docker/run-build.sh, line 47 at r1](https://reviewable.io/reviews/pmem/pmemkv-jni/33#-Ltim501B-JhxiL1EFvO:-Ltim501B-JhxiL1EFvP:bl8jlg4) ([raw file](https://github.com/pmem/pmemkv-jni/blob/9d252e082e8c68fa12385e9f687b965dd64d2611/utils/docker/run-build.sh#L47)):*
> ```Shell
> elif [ "${PACKAGE_MANAGER}" = "rpm" ]; then
> 	echo $USERPASS | sudo -S rpm -i libpmemkv*.rpm
> fi
> ```

else error out
___
*[utils/docker/images/Dockerfile.fedora-31, line 39 at r1](https://reviewable.io/reviews/pmem/pmemkv-jni/33#-Ltim7OhD7QWo6UPB4fY:-Ltim7OhD7QWo6UPB4fZ:b-ybw9lp) ([raw file](https://github.com/pmem/pmemkv-jni/blob/9d252e082e8c68fa12385e9f687b965dd64d2611/utils/docker/images/Dockerfile.fedora-31#L39)):*
> ```
> # Pull base image
> FROM fedora:31
> MAINTAINER lukasz.stolarczuk@intel.com
> ```

szymon.romik
___
*[utils/docker/images/Dockerfile.ubuntu-19.10, line 39 at r1](https://reviewable.io/reviews/pmem/pmemkv-jni/33#-LtimAhT263O8wu1IlYb:-LtimAhT263O8wu1IlYc:b-ybw9lp) ([raw file](https://github.com/pmem/pmemkv-jni/blob/9d252e082e8c68fa12385e9f687b965dd64d2611/utils/docker/images/Dockerfile.ubuntu-19.10#L39)):*
> ```
> # Pull base image
> FROM ubuntu:19.10
> MAINTAINER lukasz.stolarczuk@intel.com
> ```

szymon.romik

**Review by ldorau — COMMENTED** [review]
> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/33)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

**Review by lukaszstolarczuk — COMMENTED** [review]
done

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/33#-:-Lu8B4lmAncge7jGG4Nd:bb7f2mf)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[utils/docker/run-build.sh, line 47 at r1](https://reviewable.io/reviews/pmem/pmemkv-jni/33#-Ltim501B-JhxiL1EFvO:-Lu8B2ck56XS0X6e0hh_:b-896fix) ([raw file](https://github.com/pmem/pmemkv-jni/blob/9d252e082e8c68fa12385e9f687b965dd64d2611/utils/docker/run-build.sh#L47)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

else error out
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/33#-:-Lu8BCY5DkRJoqUNRPsh:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
