### PR TITLE
Adjust to recent pmemkv API changes (commit b08d449)

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/20)

### CODE REVIEW

**Review by igchor — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/20)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[src/io_pmem_pmemkv_Database.cpp, line 126 at r1](https://reviewable.io/reviews/pmem/pmemkv-jni/20#-LiF7vsd2xjCslWfoccN:-LiF7vsd2xjCslWfoccO:btgq41k) ([raw file](https://github.com/pmem/pmemkv-jni/blob/a161fbd0e89275780577da4c1ece0601b7912d59/src/io_pmem_pmemkv_Database.cpp#L126)):*
> ```cpp
>     const auto mid = env->GetMethodID(cls, "process", METHOD_ALL_BUFFER);
>     ContextAllBuffer cxt = CONTEXT_ALL_BUFFER;
>     pmemkv_all(engine, CALLBACK_ALL_BUFFER, &cxt);
> ```

I think we should handle statuses here (and for all functions actually):
status = pmemkv_all(...)
if (status != PMEMKV_SATUS_OK) env->ThrowNew(...)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/20)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[src/io_pmem_pmemkv_Database.cpp, line 126 at r1](https://reviewable.io/reviews/pmem/pmemkv-jni/20#-LiF7vsd2xjCslWfoccN:-LiHyT8g5XL94nateQQR:b-896fix) ([raw file](https://github.com/pmem/pmemkv-jni/blob/a161fbd0e89275780577da4c1ece0601b7912d59/src/io_pmem_pmemkv_Database.cpp#L126)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think we should handle statuses here (and for all functions actually):
status = pmemkv_all(...)
if (status != PMEMKV_SATUS_OK) env->ThrowNew(...)
</blockquote></details>

Done.

**Review by igchor — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/20#-:-LiIR-vH7omLWXAoA9zN:bnfp4nl)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @igchor)

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/20#-:-LiJj6zwB9W6RVgGR58Y:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
