### PR TITLE
Replace PMEMKV_STATUS_FAILED with PMEMKV_STATUS_UNKNOWN_ERROR

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/29)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/29)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[src/io_pmem_pmemkv_Database.cpp, line 592 at r1](https://reviewable.io/reviews/pmem/pmemkv-jni/29#-LozLJH-0HwUHuRKIKpD:-LozLJH-0HwUHuRKIKpE:bw3gept) ([raw file](https://github.com/pmem/pmemkv-jni/blob/cf2ae98e344665f2462997e77f30cc4093cf8981/src/io_pmem_pmemkv_Database.cpp#L592)):*
> ```cpp
>     const char* ckey = (char*) env->GetDirectBufferAddress(key);
>     auto status = pmemkv_exists(engine, ckey, keybytes);
>     if (status == PMEMKV_STATUS_UNKNOWN_ERROR) env->ThrowNew(env->FindClass(EXCEPTION_CLASS), "pmemkv_exists() failed");
> ```

shouldn't we check if status is != OK ?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/29)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[src/io_pmem_pmemkv_Database.cpp, line 592 at r1](https://reviewable.io/reviews/pmem/pmemkv-jni/29#-LozLJH-0HwUHuRKIKpD:-LozLx_X1TGWhi3aSYKT:b-4sfhyn) ([raw file](https://github.com/pmem/pmemkv-jni/blob/cf2ae98e344665f2462997e77f30cc4093cf8981/src/io_pmem_pmemkv_Database.cpp#L592)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

shouldn't we check if status is != OK ?
</blockquote></details>

No, it is checked below.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/29)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[src/io_pmem_pmemkv_Database.cpp, line 592 at r1](https://reviewable.io/reviews/pmem/pmemkv-jni/29#-LozLJH-0HwUHuRKIKpD:-LozcuMm1Yt9mjYjI0VV:bc1kvo9) ([raw file](https://github.com/pmem/pmemkv-jni/blob/cf2ae98e344665f2462997e77f30cc4093cf8981/src/io_pmem_pmemkv_Database.cpp#L592)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

No, it is checked below.
</blockquote></details>

Can we ever get status equal to PMEMKV_STATUS_UNKNOWN_ERROR in here?

**Comment by ldorau** [comment]
Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…
> Can we ever get status equal to PMEMKV_STATUS_UNKNOWN_ERROR in here?

Yes: 
https://github.com/pmem/pmemkv/blob/master/src/libpmemkv.cc#L301:
- https://github.com/pmem/pmemkv/blob/master/src/libpmemkv.cc#L83
and:
- https://github.com/pmem/pmemkv/blob/master/src/libpmemkv.cc#L86

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/29)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[src/io_pmem_pmemkv_Database.cpp, line 592 at r1](https://reviewable.io/reviews/pmem/pmemkv-jni/29#-LozLJH-0HwUHuRKIKpD:-Lp1w2obEtzfeliHJ1yt:blnc3zp) ([raw file](https://github.com/pmem/pmemkv-jni/blob/cf2ae98e344665f2462997e77f30cc4093cf8981/src/io_pmem_pmemkv_Database.cpp#L592)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Can we ever get status equal to PMEMKV_STATUS_UNKNOWN_ERROR in here?
</blockquote></details>

Yes:
https://github.com/pmem/pmemkv/blob/master/src/libpmemkv.cc#L301:
- https://github.com/pmem/pmemkv/blob/master/src/libpmemkv.cc#L83
and:
- https://github.com/pmem/pmemkv/blob/master/src/libpmemkv.cc#L86

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/29#-:-Lp29sma19ev6e3qw6Kt:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/29)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

___
*[src/io_pmem_pmemkv_Database.cpp, line 592 at r1](https://reviewable.io/reviews/pmem/pmemkv-jni/29#-LozLJH-0HwUHuRKIKpD:-Lp2G3wu2xf5VMK5kicH:b-qc5dhd) ([raw file](https://github.com/pmem/pmemkv-jni/blob/cf2ae98e344665f2462997e77f30cc4093cf8981/src/io_pmem_pmemkv_Database.cpp#L592)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes:
https://github.com/pmem/pmemkv/blob/master/src/libpmemkv.cc#L301:
- https://github.com/pmem/pmemkv/blob/master/src/libpmemkv.cc#L83
and:
- https://github.com/pmem/pmemkv/blob/master/src/libpmemkv.cc#L86
</blockquote></details>

I think it should be:
```
if (status != PMEMKV_STATUS_OK && status != PMEMKV_STATUS_NOT_FOUND)
...
```

The function should return found/no_found value and throw error if there is any other status

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/29)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

___
*[src/io_pmem_pmemkv_Database.cpp, line 592 at r1](https://reviewable.io/reviews/pmem/pmemkv-jni/29#-LozLJH-0HwUHuRKIKpD:-Lp2JkBP3eeZhMDE2Ik2:bpx1ec7) ([raw file](https://github.com/pmem/pmemkv-jni/blob/cf2ae98e344665f2462997e77f30cc4093cf8981/src/io_pmem_pmemkv_Database.cpp#L592)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think it should be:
```
if (status != PMEMKV_STATUS_OK && status != PMEMKV_STATUS_NOT_FOUND)
...
```

The function should return found/no_found value and throw error if there is any other status
</blockquote></details>

OK, done

**Review by lukaszstolarczuk — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/29)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/29#-:-Lp3g4hC85McfleOXpd_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
