### PR TITLE
Set exceptions msg to pmemkv_errormsg()

### PR DESCRIPTION
**Pull request by igchor**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/34)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/34#-:-LvPmAhkE68S7AfykMne:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/34)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[src/io_pmem_pmemkv_Database.cpp, line 52 at r1](https://reviewable.io/reviews/pmem/pmemkv-jni/34#-LvQEhxl9Zx5EcCq9W_3:-LvQEhxl9Zx5EcCq9W_4:b-gb6fpv) ([raw file](https://github.com/pmem/pmemkv-jni/blob/939d06d5a087f43e7fb4f849925f56b3dda74d74/src/io_pmem_pmemkv_Database.cpp#L52)):*
> ```cpp
>     auto cfg = pmemkv_config_new();
>     if (config == nullptr) {
>         env->ThrowNew(env->FindClass(EXCEPTION_CLASS), "Out of memory");
> ```

here also?

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/34)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[src/io_pmem_pmemkv_Database.cpp, line 52 at r1](https://reviewable.io/reviews/pmem/pmemkv-jni/34#-LvQEhxl9Zx5EcCq9W_3:-LvQGj0l-eql1Pp1vRyY:b-896fix) ([raw file](https://github.com/pmem/pmemkv-jni/blob/939d06d5a087f43e7fb4f849925f56b3dda74d74/src/io_pmem_pmemkv_Database.cpp#L52)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

here also?
</blockquote></details>

Done.

**Review by lukaszstolarczuk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/34#-:-LvQHvMBAVTSTAsKF6TM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
