### PR TITLE
Add travis

### PR DESCRIPTION
**Pull request by annamarcink**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/23)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 9 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/23)* status: 9 of 10 files reviewed, 5 unresolved discussions (waiting on @annamarcink)

___
*[.travis.yml, line 5 at r1](https://reviewable.io/reviews/pmem/pmemkv-jni/23#-LnNkzwkBZXUkYFDpW6r:-LnNkzwkBZXUkYFDpW6s:bb7ivnj) ([raw file](https://github.com/pmem/pmemkv-jni/blob/5714d3cfb0dca8e2745a146cc8a15e1054c8a1b2/.travis.yml#L5)):*
> ```YAML
> sudo: required
> 
> language: java
> ```

jni?
___
*[utils/docker/run-build.sh, line 43 at r1](https://reviewable.io/reviews/pmem/pmemkv-jni/23#-LnNlFsZCA1xdTcVNOgv:-LnNlFsZCA1xdTcVNOgw:bpp6stj) ([raw file](https://github.com/pmem/pmemkv-jni/blob/5714d3cfb0dca8e2745a146cc8a15e1054c8a1b2/utils/docker/run-build.sh#L43)):*
> ```Shell
> 
> # build and install pmemkv
> cd ~
> ```

not needed
___
*[utils/docker/run-build.sh, line 55 at r1](https://reviewable.io/reviews/pmem/pmemkv-jni/23#-LnNlHQ4DkHFyyebV1LI:-LnNlHQ4DkHFyyebV1LJ:b-xz2paf) ([raw file](https://github.com/pmem/pmemkv-jni/blob/5714d3cfb0dca8e2745a146cc8a15e1054c8a1b2/utils/docker/run-build.sh#L55)):*
> ```Shell
> echo
> echo "#######################################################"
> echo "### Verifying building and installing of the pmemkv-jni"
> ```

similarly like in nodejs review - perhaps worth re-phrasing it
___
*[utils/docker/run-build.sh, line 58 at r1](https://reviewable.io/reviews/pmem/pmemkv-jni/23#-LnNldO--arjrnKqiuAL:-LnNldO--arjrnKqiuAM:bhe4cfj) ([raw file](https://github.com/pmem/pmemkv-jni/blob/5714d3cfb0dca8e2745a146cc8a15e1054c8a1b2/utils/docker/run-build.sh#L58)):*
> ```Shell
> echo "#######################################################"
> cd $WORKDIR
> make
> ```

pass PREFIX as prefix to this make
___
*[utils/docker/images/Dockerfile.ubuntu-19.04, line 84 at r1](https://reviewable.io/reviews/pmem/pmemkv-jni/23#-LnNmIq3AyrGi_EbdM9U:-LnNmIq3AyrGi_EbdM9V:b-6csxo6) ([raw file](https://github.com/pmem/pmemkv-jni/blob/5714d3cfb0dca8e2745a146cc8a15e1054c8a1b2/utils/docker/images/Dockerfile.ubuntu-19.04#L84)):*
> ```
> RUN ./install-libpmemobj-cpp.sh DEB
> 
> # Prepare pmemkv
> ```

as discussed -> install in image

**Review by ldorau — COMMENTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/23)* status: all files reviewed, 6 unresolved discussions (waiting on @annamarcink and @lukaszstolarczuk)

___
*[.travis.yml, line 5 at r1](https://reviewable.io/reviews/pmem/pmemkv-jni/23#-LnNkzwkBZXUkYFDpW6r:-LnRs-FN2hMMxFhzBHC5:b-fvjt1p) ([raw file](https://github.com/pmem/pmemkv-jni/blob/5714d3cfb0dca8e2745a146cc8a15e1054c8a1b2/.travis.yml#L5)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

jni?
</blockquote></details>

There is no JNI language in Travis:
https://docs.travis-ci.com/user/languages/
___
*[.travis.yml, line 13 at r2](https://reviewable.io/reviews/pmem/pmemkv-jni/23#-LnRsGs675x6GBSn90wr:-LnRsGs675x6GBSn90ws:b-kjfa9l) ([raw file](https://github.com/pmem/pmemkv-jni/blob/646aeff5037f70c4bd6840b7ba6913ed5d228203/.travis.yml#L13)):*
> ```YAML
>   matrix:
>           - TYPE=pmemkv-master OS=ubuntu OS_VER=19.04
>           # - TYPE=pmemkv-stable OS=ubuntu OS_VER=19.04
> ```

Why is it commented out? It should be removed or a comment should be added.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/23)* status: all files reviewed, 7 unresolved discussions (waiting on @annamarcink and @lukaszstolarczuk)

___
*[utils/docker/images/Dockerfile.ubuntu-19.04, line 35 at r2](https://reviewable.io/reviews/pmem/pmemkv-jni/23#-LnRvN9S3bDr8buf1DfU:-LnRvN9S3bDr8buf1DfV:bvlgbqk) ([raw file](https://github.com/pmem/pmemkv-jni/blob/646aeff5037f70c4bd6840b7ba6913ed5d228203/utils/docker/images/Dockerfile.ubuntu-19.04#L35)):*
> ```
> # Dockerfile - a 'recipe' for Docker to build an image of ubuntu-based
> #              environment prepared for running pmemkv-nodejs build and
> #	       tests.
> ```

`... for running pmemkv-jni build.` ?

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/23)* status: all files reviewed, 7 unresolved discussions (waiting on @annamarcink and @ldorau)

___
*[.travis.yml, line 5 at r1](https://reviewable.io/reviews/pmem/pmemkv-jni/23#-LnNkzwkBZXUkYFDpW6r:-LnWkoIHDFoEt4Dg7mGT:b-lnpfuo) ([raw file](https://github.com/pmem/pmemkv-jni/blob/5714d3cfb0dca8e2745a146cc8a15e1054c8a1b2/.travis.yml#L5)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

There is no JNI language in Travis:
https://docs.travis-ci.com/user/languages/
</blockquote></details>

that's correct (that's why I put "?" ;) ). Anyway, perhaps "cpp" language can be use here... I think it might be more suitable then java...?
___
*[.travis.yml, line 13 at r2](https://reviewable.io/reviews/pmem/pmemkv-jni/23#-LnRsGs675x6GBSn90wr:-LnWl3JZ-31sgyISliW8:b1j7wj) ([raw file](https://github.com/pmem/pmemkv-jni/blob/646aeff5037f70c4bd6840b7ba6913ed5d228203/.travis.yml#L13)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Why is it commented out? It should be removed or a comment should be added.
</blockquote></details>

we commented this out since we won't use it for now, but when stable 1.0 branch will be available we want to enable it.. anyway, we can remove it that's not big deal
___
*[utils/docker/run-build.sh, line 55 at r1](https://reviewable.io/reviews/pmem/pmemkv-jni/23#-LnNlHQ4DkHFyyebV1LI:-LnWlru_3q_sf_UnSnuT:bt6cqh6) ([raw file](https://github.com/pmem/pmemkv-jni/blob/5714d3cfb0dca8e2745a146cc8a15e1054c8a1b2/utils/docker/run-build.sh#L55)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

similarly like in nodejs review - perhaps worth re-phrasing it
</blockquote></details>

actually here we don't execute tests (and this comment we'll remember to update when tests will be delivered, since is next to an executed code)
___
*[utils/docker/run-build.sh, line 58 at r1](https://reviewable.io/reviews/pmem/pmemkv-jni/23#-LnNldO--arjrnKqiuAL:-LnWlKW_EhjZLtGKb2dP:b1p051i) ([raw file](https://github.com/pmem/pmemkv-jni/blob/5714d3cfb0dca8e2745a146cc8a15e1054c8a1b2/utils/docker/run-build.sh#L58)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

pass PREFIX as prefix to this make
</blockquote></details>

actually it should be used with `make install`, I believe (please check where in Makefile this prefix is used)
___
*[utils/docker/images/Dockerfile.ubuntu-19.04, line 35 at r2](https://reviewable.io/reviews/pmem/pmemkv-jni/23#-LnRvN9S3bDr8buf1DfU:-LnWlSfY3htBm5HnY6-R:bs0gv2c) ([raw file](https://github.com/pmem/pmemkv-jni/blob/646aeff5037f70c4bd6840b7ba6913ed5d228203/utils/docker/images/Dockerfile.ubuntu-19.04#L35)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`... for running pmemkv-jni build.` ?
</blockquote></details>

I'd leave it as is, since we may add and run some tests in future and we want remember to update this brief description ;)
___
*[utils/docker/images/Dockerfile.ubuntu-19.04, line 66 at r2](https://reviewable.io/reviews/pmem/pmemkv-jni/23#-LnWliBg0FOdL-4hWuUc:-LnWliBg0FOdL-4hWuUd:b-y7230u) ([raw file](https://github.com/pmem/pmemkv-jni/blob/646aeff5037f70c4bd6840b7ba6913ed5d228203/utils/docker/images/Dockerfile.ubuntu-19.04#L66)):*
> ```
> 	libtool \
> 	libunwind8-dev \
> 	maven \
> ```

is it required here?

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/23)* status: all files reviewed, 6 unresolved discussions (waiting on @annamarcink and @ldorau)

___
*[utils/docker/run-build.sh, line 55 at r1](https://reviewable.io/reviews/pmem/pmemkv-jni/23#-LnNlHQ4DkHFyyebV1LI:-LnWoY_iBSk2MN1JQSjF:b-16g1e3) ([raw file](https://github.com/pmem/pmemkv-jni/blob/5714d3cfb0dca8e2745a146cc8a15e1054c8a1b2/utils/docker/run-build.sh#L55)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

actually here we don't execute tests (and this comment we'll remember to update when tests will be delivered, since is next to an executed code)
</blockquote></details>

to be absolutely precise we do run test :D (one, empty test, but still... ;) ). So leave it as it is now, please. Sry for confusion

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/23)* status: all files reviewed, 6 unresolved discussions (waiting on @annamarcink and @lukaszstolarczuk)

___
*[.travis.yml, line 5 at r1](https://reviewable.io/reviews/pmem/pmemkv-jni/23#-LnNkzwkBZXUkYFDpW6r:-LnXgoJo2TaptaanOhDd:be02hp) ([raw file](https://github.com/pmem/pmemkv-jni/blob/5714d3cfb0dca8e2745a146cc8a15e1054c8a1b2/.travis.yml#L5)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

that's correct (that's why I put "?" ;) ). Anyway, perhaps "cpp" language can be use here... I think it might be more suitable then java...?
</blockquote></details>

'cpp' can be if it works
___
*[.travis.yml, line 13 at r2](https://reviewable.io/reviews/pmem/pmemkv-jni/23#-LnRsGs675x6GBSn90wr:-LnXfTvY2NE6zL_TRNPG:bmkxtc7) ([raw file](https://github.com/pmem/pmemkv-jni/blob/646aeff5037f70c4bd6840b7ba6913ed5d228203/.travis.yml#L13)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

we commented this out since we won't use it for now, but when stable 1.0 branch will be available we want to enable it.. anyway, we can remove it that's not big deal
</blockquote></details>

So please add the comment like:
```
# XXX enable it when the 'stable-1.0' branch is available
```
___
*[utils/docker/images/Dockerfile.ubuntu-19.04, line 35 at r2](https://reviewable.io/reviews/pmem/pmemkv-jni/23#-LnRvN9S3bDr8buf1DfU:-LnXg7sA7AlNo96_mMSz:b-51x84o) ([raw file](https://github.com/pmem/pmemkv-jni/blob/646aeff5037f70c4bd6840b7ba6913ed5d228203/utils/docker/images/Dockerfile.ubuntu-19.04#L35)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'd leave it as is, since we may add and run some tests in future and we want remember to update this brief description ;)
</blockquote></details>

But it is **pmemkv-jni** repo, not "pmemkv-nodejs"...

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/23)* status: all files reviewed, 6 unresolved discussions (waiting on @annamarcink, @ldorau, and @lukaszstolarczuk)

___
*[utils/docker/images/Dockerfile.ubuntu-19.04, line 35 at r2](https://reviewable.io/reviews/pmem/pmemkv-jni/23#-LnRvN9S3bDr8buf1DfU:-LozOjQk4q7oDfBuuAd7:bxim9j7) ([raw file](https://github.com/pmem/pmemkv-jni/blob/646aeff5037f70c4bd6840b7ba6913ed5d228203/utils/docker/images/Dockerfile.ubuntu-19.04#L35)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

But it is **pmemkv-jni** repo, not "pmemkv-nodejs"...
</blockquote></details>

"jni" yes, fix this :)
"build" instead of "build and tests" no, leave it as is ;)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/23)* status: all files reviewed, 7 unresolved discussions (waiting on @annamarcink, @ldorau, and @lukaszstolarczuk)

___
*[utils/docker/images/Dockerfile.ubuntu-19.04, line 35 at r2](https://reviewable.io/reviews/pmem/pmemkv-jni/23#-LozT4dADDFrVFpsJW4Q:-LozT4dB2UsxwJVBCJPj:bxh3sy4) ([raw file](https://github.com/pmem/pmemkv-jni/blob/646aeff5037f70c4bd6840b7ba6913ed5d228203/utils/docker/images/Dockerfile.ubuntu-19.04#L35)):*
> ```
> # Dockerfile - a 'recipe' for Docker to build an image of ubuntu-based
> #              environment prepared for running pmemkv-nodejs build and
> #	       tests.
> ```

Please fix the whitespace -  replace the tab with spaces

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/23)* status: all files reviewed, 7 unresolved discussions (waiting on @annamarcink and @lukaszstolarczuk)

___
*[utils/docker/images/Dockerfile.ubuntu-19.04, line 35 at r2](https://reviewable.io/reviews/pmem/pmemkv-jni/23#-LnRvN9S3bDr8buf1DfU:-LozWnXfAlJVixGYzrQq:b-7i2vl4) ([raw file](https://github.com/pmem/pmemkv-jni/blob/646aeff5037f70c4bd6840b7ba6913ed5d228203/utils/docker/images/Dockerfile.ubuntu-19.04#L35)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

"jni" yes, fix this :)
"build" instead of "build and tests" no, leave it as is ;)
</blockquote></details>

... so only replace "pmemkv-nodejs" with "pmemkv-jni" ;-)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/23)* status: all files reviewed, 8 unresolved discussions (waiting on @annamarcink and @lukaszstolarczuk)

___
*[.travis.yml, line 13 at r2](https://reviewable.io/reviews/pmem/pmemkv-jni/23#-Lp7dTzN3nKm3DH9kpzf:-Lp7dTzN3nKm3DH9kpzg:bj4s80p) ([raw file](https://github.com/pmem/pmemkv-jni/blob/646aeff5037f70c4bd6840b7ba6913ed5d228203/.travis.yml#L13)):*
> ```
>           - TYPE=pmemkv-master OS=ubuntu OS_VER=19.04
>           # - TYPE=pmemkv-stable OS=ubuntu OS_VER=19.04
> ```

`PUSH_IMAGE=1` should be added to both these lines

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 10 files at r1, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/23)* status: all files reviewed, 7 unresolved discussions (waiting on @annamarcink and @lukaszstolarczuk)

___
*[utils/docker/run-build.sh, line 57 at r3](https://reviewable.io/reviews/pmem/pmemkv-jni/23#-Lq6WkRn1otRKmAAuO79:-Lq6WkRo1kkbHlT2TVlx:b5wb5nf) ([raw file](https://github.com/pmem/pmemkv-jni/blob/3fe7d4fea638b9b5750aca9c1564d0ce3bb8d33c/utils/docker/run-build.sh#L57)):*
> ```Shell
> cd $WORKDIR
> make
> echo $USERPASS | sudo -S make install PREFIX="${PREFIX}"
> ```

`make install prefix=${PREFIX}`

**Review by annamarcink — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/23)* status: 7 of 10 files reviewed, 7 unresolved discussions (waiting on @ldorau and @lukaszstolarczuk)

___
*[.travis.yml, line 5 at r1](https://reviewable.io/reviews/pmem/pmemkv-jni/23#-LnNkzwkBZXUkYFDpW6r:-Lq6Tfy30fYiS1PlwiCv:b-896fix) ([raw file](https://github.com/pmem/pmemkv-jni/blob/5714d3cfb0dca8e2745a146cc8a15e1054c8a1b2/.travis.yml#L5)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

'cpp' can be if it works
</blockquote></details>

Done.
___
*[.travis.yml, line 13 at r2](https://reviewable.io/reviews/pmem/pmemkv-jni/23#-LnRsGs675x6GBSn90wr:-Lq6TiOE4m36sO1pUMLo:b-896fix) ([raw file](https://github.com/pmem/pmemkv-jni/blob/646aeff5037f70c4bd6840b7ba6913ed5d228203/.travis.yml#L13)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

So please add the comment like:
```
# XXX enable it when the 'stable-1.0' branch is available
```
</blockquote></details>

Done.
___
*[.travis.yml, line 13 at r2](https://reviewable.io/reviews/pmem/pmemkv-jni/23#-Lp7dTzN3nKm3DH9kpzf:-Lq6TlMTEo0yIwWXwgRc:b-896fix) ([raw file](https://github.com/pmem/pmemkv-jni/blob/646aeff5037f70c4bd6840b7ba6913ed5d228203/.travis.yml#L13)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>           - TYPE=pmemkv-master OS=ubuntu OS_VER=19.04
>           # - TYPE=pmemkv-stable OS=ubuntu OS_VER=19.04
> ```

`PUSH_IMAGE=1` should be added to both these lines
</blockquote></details>

Done.
___
*[utils/docker/run-build.sh, line 43 at r1](https://reviewable.io/reviews/pmem/pmemkv-jni/23#-LnNlFsZCA1xdTcVNOgv:-Lq6TyKNASH7j3fu8_-8:b-896fix) ([raw file](https://github.com/pmem/pmemkv-jni/blob/5714d3cfb0dca8e2745a146cc8a15e1054c8a1b2/utils/docker/run-build.sh#L43)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

not needed
</blockquote></details>

Done.
___
*[utils/docker/run-build.sh, line 58 at r1](https://reviewable.io/reviews/pmem/pmemkv-jni/23#-LnNldO--arjrnKqiuAL:-Lq6ULKs1QjrE8KIlF03:b-896fix) ([raw file](https://github.com/pmem/pmemkv-jni/blob/5714d3cfb0dca8e2745a146cc8a15e1054c8a1b2/utils/docker/run-build.sh#L58)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

actually it should be used with `make install`, I believe (please check where in Makefile this prefix is used)
</blockquote></details>

Done.
___
*[utils/docker/run-build.sh, line 57 at r3](https://reviewable.io/reviews/pmem/pmemkv-jni/23#-Lq6WkRn1otRKmAAuO79:-LqGkIfC7idg5Xw8Nzug:b-896fix) ([raw file](https://github.com/pmem/pmemkv-jni/blob/3fe7d4fea638b9b5750aca9c1564d0ce3bb8d33c/utils/docker/run-build.sh#L57)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`make install prefix=${PREFIX}`
</blockquote></details>

Done.
___
*[utils/docker/images/Dockerfile.ubuntu-19.04, line 35 at r2](https://reviewable.io/reviews/pmem/pmemkv-jni/23#-LnRvN9S3bDr8buf1DfU:-Lq6UVGj2v7pzRxN0BXC:b-896fix) ([raw file](https://github.com/pmem/pmemkv-jni/blob/646aeff5037f70c4bd6840b7ba6913ed5d228203/utils/docker/images/Dockerfile.ubuntu-19.04#L35)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

... so only replace "pmemkv-nodejs" with "pmemkv-jni" ;-)
</blockquote></details>

Done.
___
*[utils/docker/images/Dockerfile.ubuntu-19.04, line 35 at r2](https://reviewable.io/reviews/pmem/pmemkv-jni/23#-LozT4dADDFrVFpsJW4Q:-Lq6U_aaBcdZ2kpQt1sA:b-896fix) ([raw file](https://github.com/pmem/pmemkv-jni/blob/646aeff5037f70c4bd6840b7ba6913ed5d228203/utils/docker/images/Dockerfile.ubuntu-19.04#L35)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please fix the whitespace -  replace the tab with spaces
</blockquote></details>

Done.
___
*[utils/docker/images/Dockerfile.ubuntu-19.04, line 66 at r2](https://reviewable.io/reviews/pmem/pmemkv-jni/23#-LnWliBg0FOdL-4hWuUc:-LqGkJnX0BH18C_864Gf:b-896fix) ([raw file](https://github.com/pmem/pmemkv-jni/blob/646aeff5037f70c4bd6840b7ba6913ed5d228203/utils/docker/images/Dockerfile.ubuntu-19.04#L66)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

is it required here?
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/23)* status: all files reviewed, 6 unresolved discussions (waiting on @annamarcink and @lukaszstolarczuk)

___
*[utils/docker/images/Dockerfile.ubuntu-19.04, line 35 at r2](https://reviewable.io/reviews/pmem/pmemkv-jni/23#-LnRvN9S3bDr8buf1DfU:-LqKjs-RDyz8WxKeuTDu:b-e0qwl9) ([raw file](https://github.com/pmem/pmemkv-jni/blob/646aeff5037f70c4bd6840b7ba6913ed5d228203/utils/docker/images/Dockerfile.ubuntu-19.04#L35)):*
<details><summary><i>Previously, annamarcink (Anna Marcinkowska) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nothing has changed ... ?
___
*[utils/docker/images/Dockerfile.ubuntu-19.04, line 35 at r2](https://reviewable.io/reviews/pmem/pmemkv-jni/23#-LozT4dADDFrVFpsJW4Q:-LqKk2SV-DMXwwNddGt_:b-e0qwl9) ([raw file](https://github.com/pmem/pmemkv-jni/blob/646aeff5037f70c4bd6840b7ba6913ed5d228203/utils/docker/images/Dockerfile.ubuntu-19.04#L35)):*
<details><summary><i>Previously, annamarcink (Anna Marcinkowska) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nothing has changed ... ?

**Review by lukaszstolarczuk — COMMENTED** [review]
There are some issues still active, but I'd merge it as is and fix it in new PR.
:lgtm: 

> Reviewed 2 of 4 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/23#-:-LqaHaBoD55aV6ajVGj7:bjyd03d)* status: all files reviewed, 5 unresolved discussions (waiting on @annamarcink and @lukaszstolarczuk)

___
*[utils/docker/images/install-libpmemobj-cpp.sh, line 43 at r4](https://reviewable.io/reviews/pmem/pmemkv-jni/23#-LqaGliS2HyTlC7WZJEc:-LqaGliS2HyTlC7WZJEd:b-uc5qth) ([raw file](https://github.com/pmem/pmemkv-jni/blob/7b861098b40a7df337052368bf4b6e2bebbc3fa9/utils/docker/images/install-libpmemobj-cpp.sh#L43)):*
> ```Shell
> cd libpmemobj-cpp
> 
> # Merge pull request #418 from karczex/template_locks, 24.09.2019
> ```

need to update to newest release
___
*[utils/docker/images/install-pmdk.sh, line 42 at r4](https://reviewable.io/reviews/pmem/pmemkv-jni/23#-LqaHL7a-0MwmhZzzxlm:-LqaHL7a-0MwmhZzzxln:b-uc5qth) ([raw file](https://github.com/pmem/pmemkv-jni/blob/7b861098b40a7df337052368bf4b6e2bebbc3fa9/utils/docker/images/install-pmdk.sh#L42)):*
> ```Shell
> cd pmdk
> # stable-1.6: Merge pull request #3856 from pmem/stable-1.5
> git checkout 7a39dd66eef934727bbb56a3bf34460bbdd92532
> ```

need to update to newest release
___
*[utils/docker/images/prepare-pmemkv.sh, line 44 at r4](https://reviewable.io/reviews/pmem/pmemkv-jni/23#-LqaHORL5M8jtbEonglf:-LqaHORL5M8jtbEonglg:b-uc5qth) ([raw file](https://github.com/pmem/pmemkv-jni/blob/7b861098b40a7df337052368bf4b6e2bebbc3fa9/utils/docker/images/prepare-pmemkv.sh#L44)):*
> ```Shell
> 
> # commit: Merge pull request #456 from karczex/multithreaded_cmap_test; 27.09.2019
> current_pmemkv_version="70b4a1272dc0e0be1ed716ff8797092396295759"
> ```

need to update to newest release

**Pull request merged**
