### PR TITLE
Adjust to all pmemkv API changes

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/21)

### CODE REVIEW

**Review by annamarcink — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/21)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by szyrom — COMMENTED** [review]
don't we want to have both get_all and get_all_keys (second one implemented with get_all from C)? 

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/21#-:-LiOfJze7MFdQcr2ZPrw:brjvisy)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by ldorau** [comment]
> don't we want to have both get_all and get_all_keys (second one implemented with get_all from C)?
> 

Done

**Review by igchor — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/21#-:-LiTOx5H1UAvYvlF_Zb4:bnfp4nl)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @szyrom)

**Review by szyrom — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/21#-:-LiT_Xgf-O4UxHEpP2ER:bnfp4nl)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @szyrom)

**Pull request merged**
