### PR TITLE
Change string to std::string.

### PR DESCRIPTION
**Pull request by igchor**
Do not expect using std::string.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/15)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/15#-:-LfZj3r738qDOrV7EXaE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by annamarcink — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/15#-:-LggGNPM75o6CcU7_-xu:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by lukaszstolarczuk** [comment]
@annamarcink, is this all that's required for java to build properly (for now)?

**Review by annamarcink — COMMENTED** [review]
Yes

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/15#-:-LggHkW34QUhg24tqP55:b2nhswy)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by szyrom — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-jni/15#-:-LggVXCCC4gw4H-5VtR3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
